### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by dabrahams** [tav/git-review#1]
http://gitreview.com/ is a dead link for me, but this looks hugely interesting!

**Comment by tav** [comment]
Hey Dave,

Sorry the server was down. The project is alive and will definitely be developed into the future. The server is back up again. Here are a few links that show it in action:
- http://gitreview.com/commit/ampify/22d3c2311e352c1dfb4586a50a5bc87a73bc15ef
- http://gitreview.com/build/59001
- http://gitreview.com/review/ampify/yncyrydybyl/test_the_tests/2

Do drop by the #esp channel on irc.freenode.net and say hi if you're interested in this kind of stuff...

## 

Cheers, tav
